apiVersion: v1
kind: Secret
metadata:
  name: secret-10
data:
  URL: Z29vZ2xlLmNvbQ==
  FQDN: d3d3Lmdvb2dsZS5jb20=
---
kind: Pod
apiVersion: v1
metadata:
  name: debug-secret-01
spec:
  containers:
    - name: debug
      image: rkalluru/debug
      envFrom:
        - secretRef:
            name: secret-10