apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue-schema
spec:
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: DB_TYPE
              value: mongo
            - name: APP_GIT_URL
              value: https://github.com/roboshop-devops-project-v3/catalogue
            - name: DB_HOST
              value: mongodb-dev.tejadevopsb81.icu
            - name: SCHEMA_FILE
              value: db/master-data.js
      restartPolicy: Never