apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
          ports:
            - containerPort: 80
          env:
            - name: CATALOGUE_HOST
              value: catalogue
            - name: CATALOGUE_PORT
              value: "8080"
            - name: USER_HOST
              value: user
            - name: USER_PORT
              value: "8080"
            - name: CART_HOST
              value: cart
            - name: CART_PORT
              value: "8080"
            - name: SHIPPING_HOST
              value: shipping
            - name: SHIPPING_PORT
              value: "8080"
            - name: PAYMENT_HOST
              value: payment
            - name: PAYMENT_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
          ports:
            - containerPort: 8080
          env:
            - name: MONGO
              value: "true"
            - name: MONGO_URL
              value: "mongodb://mongodb-dev.tejadevopsb81.icu:27017/catalogue"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  type: ClusterIP
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue-schema
spec:
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: DB_TYPE
              value: mongo
            - name: APP_GIT_URL
              value: https://github.com/roboshop-devops-project-v3/catalogue
            - name: DB_HOST
              value: mongodb-dev.tejadevopsb81.icu
            - name: SCHEMA_FILE
              value: db/master-data.js
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
          ports:
            - containerPort: 8080
          env:
            - name: MONGO
              value: "true"
            - name: MONGO_URL
              value: "mongodb://mongodb-dev.tejadevopsb81.icu:27017/users"
            - name: REDIS_URL
              value: "redis://redis-dev.tejadevopsb81.icu:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
          ports:
            - containerPort: 8080
          env:
            - name: CATALOGUE_HOST
              value: catalogue
            - name: CATALOGUE_PORT
              value: "8080"
            - name: REDIS_HOST
              value: redis-dev.tejadevopsb81.icu
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
          ports:
            - containerPort: 8080
          env:
            - name: CART_ENDPOINT
              value: "cart:8080"
            - name: DB_HOST
              value: mysql-dev.tejadevopsb81.icu
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  type: ClusterIP
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
          ports:
            - containerPort: 8080
          env:
            - name: CART_HOST
              value: cart
            - name: CART_PORT
              value: "8080"
            - name: USER_HOST
              value: user
            - name: USER_PORT
              value: "8080"
            - name: AMQP_HOST
              value: rabbitmq-dev.tejadevopsb81.icu
            - name: AMQP_USER
              value: roboshop
            - name: AMQP_PASS
              value: roboshop123
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080