apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema
spec:
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: DB_TYPE
              value: mysql
            - name: APP_GIT_URL
              value: https://github.com/roboshop-devops-project-v3/shipping
            - name: DB_HOST
              value: mysql-dev.tejadevopsb81.icu
            - name: SCHEMA_FILE
              value: db/schema.sql
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: RoboShop@1
      restartPolicy: Never